language: python

env:
  global:
    - CIBW_TEST_REQUIRES=numpy cython

matrix:
  include:
    - sudo: required
      services:
        - docker
      env: PIP=pip
    - os: osx
      language: generic
      env: PIP=pip2

script:
  - $PIP install cibuildwheel==0.10.2
  - cibuildwheel --output-dir wheelhouse
