language: python

matrix:
  include:
    - sudo: required
      services:
        - docker
      env: PIP=pip
    - os: osx
      language: generic
      env: PIP=pip

script:
  - $PIP install cibuildwheel==0.10.2 numpy cython
  - cibuildwheel --output-dir wheelhouse
